os: Visual Studio 2015
version: 0.9.{build}

install:
    # https://www.appveyor.com/docs/installed-software/#qt
    - set QTDIR=C:\Qt\5.7\msvc2015_64
    - set PATH=%QTDIR%\bin;%PATH%
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    - qmake -v

build_script:
    - qmake
    - nmake /NOLOGO

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\projects\lib\tests\
    - qmake
    - nmake /NOLOGO
    - '%cd%\chessboard\tst_board'
